In [1]:
import numpy as np

Suppose that the input volume is a numpy array X.


with shape 11,11,4

In [7]:
X = np.random.randint(low = 0, high = 225,size = [11,11,4])

In [28]:
X

array([[[ 64, 159,  72, 132],
        [139,   9,  66,  62],
        [ 11,  39, 155,  36],
        [ 45, 193,  68,  14],
        [133,  56, 158, 219],
        [121, 190, 203,  26],
        [157,  11, 131, 106],
        [201, 190, 180, 218],
        [ 32, 181, 188,  97],
        [ 66, 165,  37, 163],
        [102, 200,  91, 164]],

       [[ 25,   8, 128, 193],
        [ 61, 150, 150, 211],
        [ 12,  53,  64,  64],
        [131,   7, 148,   0],
        [166,  78, 184, 198],
        [156, 152,  48,  98],
        [173,  39,  81, 119],
        [ 29, 128,   8, 197],
        [177,  48, 217, 195],
        [125, 206, 156, 213],
        [219, 163, 215, 145]],

       [[140,  24, 211, 186],
        [211,  95, 168,  67],
        [ 18, 112, 101,   7],
        [ 20, 153, 113, 110],
        [106, 142,  26, 172],
        [ 21,   6,  80,  36],
        [ 20, 137,  73, 127],
        [ 79,  46,  49, 127],
        [194,  65,  67, 220],
        [217,  66,  25,   0],
        [ 72, 100, 204,  32]],

    

In [10]:
X.shape

(11, 11, 4)

Suppose further that we use no zero padding (P=0), 
that the filter size is F=5
and that the stride is S=2.

In [11]:
p = 0
f = 5
s = 2

print('output layer size is : {}'.format(((x.shape[0]- f + 2*p)/s)+1))

output layer size is : 4.0


output layer shape will be 4X4Xnumber of filter

In [14]:
W0 = np.random.rand(5,5,4)

In [17]:
b0 = np.random.rand(1)

shape of output vector will be 4*4

In [25]:
V = np.zeros([4,4,2])

## New Example

In [166]:
X = np.array([[[0,0,1],
               [1,0,1],
               [2,1,2],
               [2,0,0],
               [0,0,2]],
              
              [[1,1,2],
               [1,2,0],
               [2,2,0],
               [0,2,1],
               [0,0,1]],
              
              [[1,0,2],
               [2,2,2],
               [1,1,0],
               [1,0,2],
               [0,2,1]],
              
              [[2,2,0],
               [1,0,0],
               [0,0,1],
               [0,1,1],
               [0,0,2]],              
              
              [[0,2,1],
               [2,0,0],
               [1,0,1],
               [2,2,1],
               [2,1,0]]])

Red Matrix

In [167]:
X[:,:,0]

array([[0, 1, 2, 2, 0],
       [1, 1, 2, 0, 0],
       [1, 2, 1, 1, 0],
       [2, 1, 0, 0, 0],
       [0, 2, 1, 2, 2]])

Green Matrix

In [168]:
X[:,:,1]

array([[0, 0, 1, 0, 0],
       [1, 2, 2, 2, 0],
       [0, 2, 1, 0, 2],
       [2, 0, 0, 1, 0],
       [2, 0, 0, 2, 1]])

Blue Matrix

In [169]:
X[:,:,2]

array([[1, 1, 2, 0, 2],
       [2, 0, 0, 1, 1],
       [2, 2, 0, 2, 1],
       [0, 0, 1, 1, 2],
       [1, 0, 1, 1, 0]])

## filter

### Filter - 1 W0

In [170]:
W0 =  np.array([[[0,1,1],
               [-1,0,1],
               [1,-1,1]],
              
              [[0,0,1],
               [0,-1,0],
               [-1,1,1]],
              
              [[0,-1,1],
               [-1,-1,1],
               [1,0,0]]])

In [171]:
W0[:,:,0]

array([[ 0, -1,  1],
       [ 0,  0, -1],
       [ 0, -1,  1]])

In [172]:
W0[:,:,1]

array([[ 1,  0, -1],
       [ 0, -1,  1],
       [-1, -1,  0]])

In [173]:
W0[:,:,2]

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [174]:
pad_x = np.pad(X,((1,1), (1,1), (0, 0)))

In [175]:
b0 = 1

In [176]:
stride1 = 2

In [202]:
V = np.zeros([3,3,1])

In [203]:
V[0,0,0] = np.sum(pad_x[:3,:3,:] * W0) + b0
V[0,1,0] = np.sum(pad_x[:3,2:5,:] * W0) + b0
V[0,2,0] = np.sum(pad_x[:3,4:7,:] * W0) + b0

V[1,0,0] = np.sum(pad_x[2:5,:3,:] * W0) + b0
V[1,1,0] = np.sum(pad_x[2:5,2:5,:] * W0) + b0
V[1,2,0] = np.sum(pad_x[2:5,4:7,:] * W0) + b0

V[2,0,0] = np.sum(pad_x[4:7,:3,:] * W0) + b0
V[2,1,0] = np.sum(pad_x[4:7,2:5,:] * W0) + b0
V[2,2,0] = np.sum(pad_x[4:7,4:7,:] * W0) + b0

In [204]:
V[:,:,0]

array([[ 2., -7.,  1.],
       [ 0.,  3.,  7.],
       [-4.,  3.,  5.]])

### Filter - 2 W1

In [190]:
W1 =  np.array([[[0,1,0],
               [-1,0,0],
               [1,-1,0]],
              
              [[1,1,-1],
               [-1,1,0],
               [1,1,-1]],
              
              [[0,0,0],
               [-1,1,-1],
               [-1,1,-1]]])

In [191]:
W1[:,:,0]

array([[ 0, -1,  1],
       [ 1, -1,  1],
       [ 0, -1, -1]])

In [189]:
W1[:,:,1]

array([[ 1,  0, -1],
       [ 1,  1,  1],
       [ 0,  1,  1]])

In [165]:
pad_x[2:5,2:5,2]

array([[0, 0, 1],
       [2, 0, 0],
       [0, 1, 1]])

In [192]:
W1[:,:,2]

array([[ 0,  0,  0],
       [-1,  0, -1],
       [ 0, -1, -1]])

In [193]:
b1 = 0

Conv layer calculation function

In [215]:
filter_size1 = 3

def cal_conv_layer(filter_size1,weight_mat,bias1,inp_layer,stride_val,padding_val):
    v1 = np.zeros([filter_size1,filter_size1,1])
    
    pad_inp = np.pad(inp_layer,((padding_val,padding_val), (padding_val,padding_val), (0, 0)))
    
    for i in range(filter_size1):
        for j in range(filter_size1):
            v1[i,j,0] = np.sum(pad_inp[0 + i*stride_val : filter_size1 + i*stride_val,0 + j*stride_val : filter_size1 + j*stride_val,:] * weight_mat) + bias1
    
    return v1
    

In [218]:
cal_conv_layer(3,W1,b1,X,2,1)[:,:,0]

array([[-1.,  2.,  1.],
       [-2., -2.,  1.],
       [ 3.,  3.,  3.]])

In [219]:
cal_conv_layer(3,W0,b0,X,2,1)[:,:,0]

array([[ 2., -7.,  1.],
       [ 0.,  3.,  7.],
       [-4.,  3.,  5.]])